import React, { useState, useRef, useEffect } from 'react';
import { Row, Col } from 'antd';
import { Select, Option, Input } from 'teespace-core';
import { useStore } from '../../stores';

const countries = [
  ['Abkhazia', '+7 840'],
  ['Abkhazia', '+7 940'],
  ['Abkhazia', '+995 44'],
  ['Afghanistan', '+93'],
  ['Aland Islands', '+358 18'],
  ['Albania', '+355'],
  ['Algeria', '+213'],
  ['American Samoa', '+1 684'],
  ['Andorra', '+376'],
  ['Angola', '+244'],
  ['Anguilla', '+1 264'],
  ['Antigua & Barbuda', '+1 268'],
  ['Argentina', '+54'],
  ['Armenia', '+374'],
  ['Aruba', '+297'],
  ['Ascension', '+247'],
  ['Australia', '+61'],
  ['Australian External Territories', '+672'],
  ['Austria', '+43'],
  ['Azerbaijan', '+994'],
  ['Bahamas', '+1 242'],
  ['Bahrain', '+973'],
  ['Bangladesh', '+880'],
  ['Barbados', '+1 246'],
  ['Barbuda', '+1 268'],
  ['Belarus', '+375'],
  ['Belgium', '+32'],
  ['Belize', '+501'],
  ['Benin', '+229'],
  ['Bermuda', '+1 441'],
  ['Bhutan', '+975'],
  ['Bolivia', '+591'],
  ['Bosnia & Herzegovina', '+387'],
  ['Botswana', '+267'],
  ['Brazil', '+55'],
  ['British Indian Ocean Territory', '+246'],
  ['British Virgin Islands', '+1 284'],
  ['Brunei', '+673'],
  ['Bulgaria', '+359'],
  ['Burkina Faso', '+226'],
  ['Burundi', '+257'],
  ['Cambodia', '+855'],
  ['Cameroon', '+237'],
  ['Canada', '+1'],
  ['Cape Verde', '+238'],
  ['Caribbean Netherlands', '+599 7'],
  ['Cayman Islands', '+1 345'],
  ['Central African Republic', '+236'],
  ['Chad', '+235'],
  ['Chile', '+56'],
  ['China', '+86'],
  ['Christmas Island', '+61'],
  ['Cocos (Keeling) Islands', '+61'],
  ['Colombia', '+57'],
  ['Comoros', '+269'],
  ['Congo - Brazzaville', '+242'],
  ['Congo - Kinshasa', '+243'],
  ['Cook Islands', '+682'],
  ['Costa Rica', '+506'],
  ['Cote d’Ivoire', '+225'],
  ['Croatia', '+385'],
  ['Cuba', '+53'],
  ['Curacao', '+599 9'],
  ['Cyprus', '+357'],
  ['Czech Republic', '+420'],
  ['Denmark', '+45'],
  ['Diego Garcia', '+246'],
  ['Djibouti', '+253'],
  ['Dominica', '+1 767'],
  ['Dominican Republic', '+1 809'],
  ['Dominican Republic', '+1 829'],
  ['Dominican Republic', '+1 849'],
  ['Ecuador', '+593'],
  ['Egypt', '+20'],
  ['El Salvador', '+503'],
  ['Equatorial Guinea', '+240'],
  ['Eritrea', '+291'],
  ['Estonia', '+372'],
  ['Ethiopia', '+251'],
  ['Falkland Islands', '+500'],
  ['Faroe Islands', '+298'],
  ['Fiji', '+679'],
  ['Finland', '+358'],
  ['France', '+33'],
  ['French Guiana', '+594'],
  ['French Polynesia', '+689'],
  ['Gabon', '+241'],
  ['Gambia', '+220'],
  ['Georgia', '+995'],
  ['Germany', '+49'],
  ['Ghana', '+233'],
  ['Gibraltar', '+350'],
  ['Greece', '+30'],
  ['Greenland', '+299'],
  ['Grenada', '+1 473'],
  ['Guadeloupe', '+590'],
  ['Guam', '+1 671'],
  ['Guatemala', '+502'],
  ['Guernsey', '+44'],
  ['Guinea', '+224'],
  ['Guinea-Bissau', '+245'],
  ['Guyana', '+592'],
  ['Haiti', '+509'],
  ['Honduras', '+504'],
  ['Hong Kong SAR China', '+852'],
  ['Hungary', '+36'],
  ['Iceland', '+354'],
  ['India', '+91'],
  ['Indonesia', '+62'],
  ['Iran', '+98'],
  ['Iraq', '+964'],
  ['Ireland', '+353'],
  ['Israel', '+972'],
  ['Italy', '+39'],
  ['Jamaica', '+1 876'],
  ['Japan', '+81'],
  ['Jersey', '+44'],
  ['Jordan', '+962'],
  ['Kazakhstan', '+7 6'],
  ['Kazakhstan', '+7 7'],
  ['Kenya', '+254'],
  ['Kiribati', '+686'],
  ['Kuwait', '+965'],
  ['Kyrgyzstan', '+996'],
  ['Laos', '+856'],
  ['Latvia', '+371'],
  ['Lebanon', '+961'],
  ['Lesotho', '+266'],
  ['Liberia', '+231'],
  ['Libya', '+218'],
  ['Liechtenstein', '+423'],
  ['Lithuania', '+370'],
  ['Luxembourg', '+352'],
  ['Macau SAR China', '+853'],
  ['Macedonia', '+389'],
  ['Madagascar', '+261'],
  ['Malawi', '+265'],
  ['Malaysia', '+60'],
  ['Maldives', '+960'],
  ['Mali', '+223'],
  ['Malta', '+356'],
  ['Marshall Islands', '+692'],
  ['Martinique', '+596'],
  ['Mauritania', '+222'],
  ['Mauritius', '+230'],
  ['Mayotte', '+262'],
  ['Mexico', '+52'],
  ['Micronesia', '+691'],
  ['Moldova', '+373'],
  ['Monaco', '+377'],
  ['Mongolia', '+976'],
  ['Montenegro', '+382'],
  ['Montserrat', '+1 664'],
  ['Morocco', '+212'],
  ['Mozambique', '+258'],
  ['Myanmar (Burma)', '+95'],
  ['Namibia', '+264'],
  ['Nauru', '+674'],
  ['Nepal', '+977'],
  ['Netherlands', '+31'],
  ['New Caledonia', '+687'],
  ['New Zealand', '+64'],
  ['Nicaragua', '+505'],
  ['Niger', '+227'],
  ['Nigeria', '+234'],
  ['Niue', '+683'],
  ['Norfolk Island', '+672'],
  ['North Korea', '+850'],
  ['Northern Mariana Islands', '+1 670'],
  ['Norway', '+47'],
  ['Oman', '+968'],
  ['Pakistan', '+92'],
  ['Palau', '+680'],
  ['Palestinian Territories', '+970'],
  ['Panama', '+507'],
  ['Papua New Guinea', '+675'],
  ['Paraguay', '+595'],
  ['Peru', '+51'],
  ['Philippines', '+63'],
  ['Pitcairn Islands', '+64'],
  ['Poland', '+48'],
  ['Portugal', '+351'],
  ['Puerto Rico', '+1 787'],
  ['Puerto Rico', '+1 939'],
  ['Qatar', '+974'],
  ['Reunion', '+262'],
  ['Romania', '+40'],
  ['Russia', '+7'],
  ['Rwanda', '+250'],
  ['Samoa', '+685'],
  ['San Marino', '+378'],
  ['Sao Tome & Principe', '+239'],
  ['Saudi Arabia', '+966'],
  ['Senegal', '+221'],
  ['Serbia', '+381'],
  ['Seychelles', '+248'],
  ['Sierra Leone', '+232'],
  ['Singapore', '+65'],
  ['Sint Eustatius', '+599 3'],
  ['Sint Maarten', '+1 721'],
  ['Slovakia', '+421'],
  ['Slovenia', '+386'],
  ['Solomon Islands', '+677'],
  ['Somalia', '+252'],
  ['South Africa', '+27'],
  ['South Georgia & South Sandwich Islands', '+500'],
  ['South Korea', '+82'],
  ['South Ossetia', '+995 34'],
  ['South Sudan', '+211'],
  ['Spain', '+34'],
  ['Sri Lanka', '+94'],
  ['St. Barthelemy', '+590'],
  ['St. Helena', '+290'],
  ['St. Kitts & Nevis', '+1 869'],
  ['St. Lucia', '+1 758'],
  ['St. Martin (France)', '+590'],
  ['St. Pierre and Miquelon', '+508'],
  ['St. Vincent and the Grenadines', '+1 784'],
  ['Sudan', '+249'],
  ['Suriname', '+597'],
  ['Svalbard', '+47 79'],
  ['Svalbard & Jan Mayen', '+47 79'],
  ['Swaziland', '+268'],
  ['Sweden', '+46'],
  ['Switzerland', '+41'],
  ['Syria', '+963'],
  ['Taiwan', '+886'],
  ['Tajikistan', '+992'],
  ['Tanzania', '+255'],
  ['Thailand', '+66'],
  ['Timor-Leste', '+670'],
  ['Togo', '+228'],
  ['Tokelau', '+690'],
  ['Tonga', '+676'],
  ['Trinidad & Tobago', '+1 868'],
  ['Tunisia', '+216'],
  ['Turkey', '+90'],
  ['Turkmenistan', '+993'],
  ['Turks & Caicos Islands', '+1 649'],
  ['Tuvalu', '+688'],
  ['U.S. Virgin Islands', '+1 340'],
  ['Uganda', '+256'],
  ['Ukraine', '+380'],
  ['United Arab Emirates', '+971'],
  ['United Kingdom', '+44'],
  ['United States', '+1'],
  ['Uruguay', '+598'],
  ['Uzbekistan', '+998'],
  ['Vanuatu', '+678'],
  ['Vatican City', '+39 06 698'],
  ['Vatican City', '+379'],
  ['Venezuela', '+58'],
  ['Vietnam', '+84'],
  ['Wallis & Futuna', '+681'],
  ['Yemen', '+967'],
  ['Zambia', '+260'],
  ['Zanzibar', '+255'],
  ['Zimbabwe', '+263'],
];
function AddFriendsByPhoneNumberHeader({
  handleNationalCodeChange,
  handlePhoneChange,
  handleFriendNickChange,
  phone,
}) {
  const { uiStore } = useStore();
  const [dropdownWidth, setDropdownWidth] = useState(0);
  const formContainer = useRef(null);

  useEffect(() => {
    if (formContainer.current) {
      setDropdownWidth(formContainer.current.clientWidth);
    }
  }, [formContainer]);
  return (
    <div ref={formContainer}>
      <Row>
        <Col span={24}>
          <Input
            placeholder="추가할 친구의 별명을 입력해 주세요."
            onChange={handleFriendNickChange}
          />
        </Col>
        <Col span={24} style={{ display: 'flex' }}>
          <Select
            defaultValue="+82"
            onChange={handleNationalCodeChange}
            style={{ width: 130 }}
            dropdownStyle={{ width: dropdownWidth }}
            optionLabelProp="title"
          >
            {countries.map(country => (
              <Option
                value={country[1].split(' ').join('')}
                title={country[1]}
                key={country[1]}
              >
                {country[1]} ({country[1].split(' ').join('').slice(1)}){' '}
                {country[0]}
              </Option>
            ))}
          </Select>
          <Input
            alert={
              phone && uiStore.addFriendByPhoneNumberButtonDisabled
                ? '숫자만 입력해 주세요'
                : ''
            }
            placeholder="'-'없이 숫자만 입력해 주세요."
            onChange={handlePhoneChange}
            value={phone}
            style={{ width: '100%' }}
          />
        </Col>
      </Row>
    </div>
  );
}

export default AddFriendsByPhoneNumberHeader;
